[package]
name = "pdl-infrastructure"
version = "0.1.0"
edition = "2021"
description = "Runtime helpers for PDL-generated ORM code"
license = "MIT"

[lib]
name = "pdl_infrastructure"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
