package mysql

var mysqlTypeDictionary = map[string]map[string]string{
	"Go": {
		"int":        "int",
		"tinyint":    "int",
		"smallint":   "int",
		"mediumint":  "int",
		"numeric":    "int",
		"bigint":     "int64",
		"float":      "float64",
		"double":     "float64",
		"decimal":    "float64",
		"bit":        "int",
		"char":       "string",
		"varchar":    "string",
		"tinytext":   "string",
		"text":       "string",
		"mediumtext": "string",
		"longtext":   "string",
		"binary":     "[]byte",
		"varbinary":  "[]byte",
		"tinyblob":   "[]byte",
		"blob":       "[]byte",
		"mediumblob": "[]byte",
		"longblob":   "[]byte",
		"enum":       "string",
		"date":       "time.Time",
		"datetime":   "time.Time",
		"time":       "string",
		"timestamp":  "time.Time",
		"year":       "int",
	},
	"Pdl": {
		"int":        "int",
		"tinyint":    "int",
		"smallint":   "int",
		"mediumint":  "int",
		"numeric":    "int",
		"bigint":     "int",
		"float":      "double",
		"double":     "double",
		"decimal":    "double",
		"bit":        "int",
		"char":       "string",
		"varchar":    "string",
		"tinytext":   "string",
		"text":       "string",
		"mediumtext": "string",
		"longtext":   "string",
		"binary":     "string",
		"varbinary":  "string",
		"tinyblob":   "string",
		"blob":       "string",
		"mediumblob": "string",
		"longblob":   "string",
		"enum":       "string",
		"date":       "string",
		"datetime":   "string",
		"time":       "string",
		"timestamp":  "string",
		"year":       "int",
	},
	"TypeScript": {
		"int":        "number",
		"tinyint":    "number",
		"smallint":   "number",
		"mediumint":  "number",
		"numeric":    "number",
		"bigint":     "number",
		"float":      "number",
		"double":     "number",
		"decimal":    "number",
		"bit":        "number",
		"char":       "string",
		"varchar":    "string",
		"tinytext":   "string",
		"text":       "string",
		"mediumtext": "string",
		"longtext":   "string",
		"binary":     "string",
		"varbinary":  "string",
		"tinyblob":   "string",
		"blob":       "string",
		"mediumblob": "string",
		"longblob":   "string",
		"enum":       "string",
		"date":       "string",
		"datetime":   "string",
		"time":       "string",
		"timestamp":  "string",
		"year":       "number",
	},
	"Php": {
		"int":        "int",
		"tinyint":    "int",
		"smallint":   "int",
		"mediumint":  "int",
		"numeric":    "int",
		"bigint":     "int",
		"float":      "float",
		"double":     "float",
		"decimal":    "float",
		"bit":        "int",
		"char":       "string",
		"varchar":    "string",
		"tinytext":   "string",
		"text":       "string",
		"mediumtext": "string",
		"longtext":   "string",
		"binary":     "string",
		"varbinary":  "string",
		"tinyblob":   "string",
		"blob":       "string",
		"mediumblob": "string",
		"longblob":   "string",
		"enum":       "string",
		"date":       "string",
		"datetime":   "string",
		"time":       "string",
		"timestamp":  "string",
		"year":       "int",
	},
}

func sqlTypeToLanguage(language string, cleanType string) string {
	languageMap, languageFound := mysqlTypeDictionary[language]
	if !languageFound {
		return "string"
	}
	typeValue, typeFound := languageMap[cleanType]
	if !typeFound {
		return "string"
	}
	return typeValue
}
