-- PostgreSQL-compatible schema translated from sample-project/manjar-schema.sql
-- Generated by automated conversion; review for semantics like ON UPDATE behaviors and full-text search equivalents.

-- Table structure for table `addresses`

DROP TABLE IF EXISTS "addresses";

CREATE TABLE "addresses" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "status" varchar(10) NOT NULL DEFAULT 'ok',
  "default_delivery" varchar(4) NOT NULL DEFAULT 'no',
  "default_pickup" varchar(4) NOT NULL DEFAULT 'no',
  "address1" varchar(255) DEFAULT NULL,
  "address2" varchar(255) DEFAULT NULL,
  "city" varchar(255) DEFAULT NULL,
  "state" varchar(255) DEFAULT NULL,
  "country" varchar(255) DEFAULT NULL,
  "phone" varchar(255) DEFAULT NULL,
  "zipcode" varchar(255) DEFAULT NULL,
  "lon" double precision DEFAULT NULL,
  "lat" double precision DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "is_test" varchar(1) NOT NULL DEFAULT 'n',
  PRIMARY KEY ("id")
);

-- Table structure for table `cache`

DROP TABLE IF EXISTS "cache";

CREATE TABLE "cache" (
  "key" varchar(255) NOT NULL,
  "value" text NOT NULL,
  "expiration" integer NOT NULL
);
CREATE UNIQUE INDEX "cache_key_unique" ON "cache" ("key");

-- Table structure for table `categories`

DROP TABLE IF EXISTS "categories";

CREATE TABLE "categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "store_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'ok',
  "slug" varchar(255) DEFAULT NULL,
  "position" bigint DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "categories_store_id_index" ON "categories" ("store_id");

-- Table structure for table `category_products`

DROP TABLE IF EXISTS "category_products";

CREATE TABLE "category_products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "store_id" bigint NOT NULL,
  "category_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "position" bigint NOT NULL DEFAULT 0,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "category_products_store_id_index" ON "category_products" ("store_id");
CREATE INDEX "category_products_category_id_index" ON "category_products" ("category_id");
CREATE INDEX "category_products_product_id_index" ON "category_products" ("product_id");

-- Table structure for table `courier_locations`

DROP TABLE IF EXISTS "courier_locations";

CREATE TABLE "courier_locations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "courier_uuid" varchar(40) NOT NULL,
  "location_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "lat" double precision NOT NULL,
  "lon" double precision NOT NULL,
  "speed" double precision NOT NULL,
  "altitude" double precision NOT NULL,
  "heading" double precision NOT NULL,
  "accuracy" double precision NOT NULL,
  "altitude_accuracy" double precision NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "courier_locations_courier_uuid_index" ON "courier_locations" ("courier_uuid");
CREATE INDEX "courier_locations_location_time_index" ON "courier_locations" ("location_time");

-- Table structure for table `courier_orders`

DROP TABLE IF EXISTS "courier_orders";

CREATE TABLE "courier_orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "courier_uuid" varchar(255) NOT NULL,
  "order_id" bigint DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'assigned',
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "order_id-index" ON "courier_orders" ("order_id");
CREATE INDEX "courier_orders_status_index" ON "courier_orders" ("status");
CREATE INDEX "courier_orders_courier_uuid_index" ON "courier_orders" ("courier_uuid");

-- Table structure for table `customization_search`

DROP TABLE IF EXISTS "customization_search";

CREATE TABLE "customization_search" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "relation_id" bigint NOT NULL,
  "customization_full_name" text NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "customization_search_user_id_index" ON "customization_search" ("user_id");
CREATE INDEX "customization_search_relation_id_index" ON "customization_search" ("relation_id");
CREATE INDEX "fulltext_index" ON "customization_search" USING gin (to_tsvector('simple', coalesce("customization_full_name", '')));

-- Table structure for table `discount_instances`

DROP TABLE IF EXISTS "discount_instances";

CREATE TABLE "discount_instances" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "store_id" bigint DEFAULT 0,
  "product_id" bigint DEFAULT 0,
  "instance_info" text NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "discount_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "discount_instances_discount_id_index" ON "discount_instances" ("discount_id");
CREATE INDEX "discount_instances_store_id_index" ON "discount_instances" ("store_id");
CREATE INDEX "discount_instances_product_id_index" ON "discount_instances" ("product_id");

-- Table structure for table `discounts`

DROP TABLE IF EXISTS "discounts";

CREATE TABLE "discounts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) DEFAULT NULL,
  "description" varchar(255) DEFAULT NULL,
  "code" varchar(128) DEFAULT NULL,
  "scope" varchar(50) NOT NULL DEFAULT 'global',
  "status" varchar(50) NOT NULL DEFAULT 'ok',
  "type" varchar(50) NOT NULL DEFAULT 'percentage',
  "value" double precision NOT NULL,
  "min_amount" double precision NOT NULL DEFAULT 0,
  "max_amount" double precision NOT NULL DEFAULT 0,
  "datetime_zone" varchar(255) NOT NULL DEFAULT 'America/New York',
  "locale" varchar(20) NOT NULL DEFAULT 'en_US',
  "currency" varchar(20) NOT NULL DEFAULT 'USD',
  "start_date" timestamp without time zone NULL DEFAULT NULL,
  "end_date" timestamp without time zone NULL DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "target" varchar(255) NOT NULL DEFAULT '1',
  "duration" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);

-- Table structure for table `failed_jobs`

DROP TABLE IF EXISTS "failed_jobs";

CREATE TABLE "failed_jobs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "uuid" varchar(255) NOT NULL,
  "connection" text NOT NULL,
  "queue" text NOT NULL,
  "payload" text NOT NULL,
  "exception" text NOT NULL,
  "failed_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" ON "failed_jobs" ("uuid");

-- Table structure for table `jobs`

DROP TABLE IF EXISTS "jobs";

CREATE TABLE "jobs" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "queue" varchar(255) NOT NULL,
  "payload" text NOT NULL,
  "attempts" smallint NOT NULL,
  "reserved_at" bigint DEFAULT NULL,
  "available_at" bigint NOT NULL,
  "created_at" bigint NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "jobs_queue_index" ON "jobs" ("queue");

-- Table structure for table `menus`

DROP TABLE IF EXISTS "menus";

CREATE TABLE "menus" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "store_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" varchar(255) NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'ok',
  "schedule" text DEFAULT NULL,
  "category_ids" text DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "menus_store_id_index" ON "menus" ("store_id");

-- Table structure for table `migrations`

DROP TABLE IF EXISTS "migrations";

CREATE TABLE "migrations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "migration" varchar(255) NOT NULL,
  "batch" integer NOT NULL,
  PRIMARY KEY ("id")
);

-- Table structure for table `notifications`

DROP TABLE IF EXISTS "notifications";

CREATE TABLE "notifications" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "type" varchar(255) NOT NULL DEFAULT 'order',
  "name" varchar(255) NOT NULL,
  "from_user_id" bigint DEFAULT NULL,
  "to_user_id" bigint DEFAULT NULL,
  "from_store_Id" bigint DEFAULT NULL,
  "to_store_id" bigint DEFAULT NULL,
  "order_id" varchar(255) DEFAULT NULL,
  "source" varchar(255) DEFAULT NULL,
  "url" varchar(255) DEFAULT NULL,
  "title" varchar(255) DEFAULT NULL,
  "body" text DEFAULT NULL,
  "unread" varchar(1) NOT NULL DEFAULT 'y',
  "notification_time" timestamp without time zone DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "data" text NOT NULL,
  "retrieved_first_time" timestamp without time zone DEFAULT NULL,
  "read_time" timestamp without time zone DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "notifications_read_index" ON "notifications" ("unread");
CREATE INDEX "notifications_fromuserid_index" ON "notifications" ("from_user_id");
CREATE INDEX "notifications_touserid_index" ON "notifications" ("to_user_id");
CREATE INDEX "notifications_fromstoreid_index" ON "notifications" ("from_store_Id");
CREATE INDEX "notifications_tostoreid_index" ON "notifications" ("to_store_id");
CREATE INDEX "notifications_orderid_index" ON "notifications" ("order_id");

-- Table structure for table `order_product`

DROP TABLE IF EXISTS "order_product";

CREATE TABLE "order_product" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "order_id" bigint DEFAULT NULL,
  "product_id" bigint DEFAULT NULL,
  "quantity" bigint NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "order_product_order_id_foreign" FOREIGN KEY ("order_id") REFERENCES "org_orders" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "order_product_product_id_foreign" FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "order_product_order_id_foreign_idx" ON "order_product" ("order_id");
CREATE INDEX "order_product_product_id_foreign_idx" ON "order_product" ("product_id");

-- Table structure for table `orders`

DROP TABLE IF EXISTS "orders";

CREATE TABLE "orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "order_id" varchar(255) NOT NULL,
  "store_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "status" varchar(255) NOT NULL,
  "notes" text NOT NULL,
  "model" text NOT NULL,
  "delivery_tax_amount" integer NOT NULL DEFAULT 0,
  "seller_total" integer NOT NULL DEFAULT 0,
  "seller_tax_amount" integer NOT NULL DEFAULT 0,
  "discount_amount" integer NOT NULL DEFAULT 0,
  "tax_amount" integer NOT NULL DEFAULT 0,
  "sub_total" integer NOT NULL DEFAULT 0,
  "total" integer NOT NULL DEFAULT 0,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "courier_uuid" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "orders_order_id_unique" ON "orders" ("order_id");
CREATE INDEX "store-id" ON "orders" ("store_id");
CREATE INDEX "user-id" ON "orders" ("user_id");

-- Table structure for table `org_orders`

DROP TABLE IF EXISTS "org_orders";

CREATE TABLE "org_orders" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint DEFAULT NULL,
  "billing_email" varchar(255) DEFAULT NULL,
  "billing_name" varchar(255) DEFAULT NULL,
  "billing_address" varchar(255) DEFAULT NULL,
  "billing_city" varchar(255) DEFAULT NULL,
  "billing_province" varchar(255) DEFAULT NULL,
  "billing_postalcode" varchar(255) DEFAULT NULL,
  "billing_phone" varchar(255) DEFAULT NULL,
  "billing_name_on_card" varchar(255) DEFAULT NULL,
  "billing_discount" integer NOT NULL DEFAULT 0,
  "billing_discount_code" varchar(255) DEFAULT NULL,
  "billing_subtotal" integer NOT NULL,
  "billing_tax" integer NOT NULL,
  "billing_total" integer NOT NULL,
  "payment_gateway" varchar(255) NOT NULL DEFAULT 'stripe',
  "shipped" boolean NOT NULL DEFAULT FALSE,
  "error" varchar(255) DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);

-- Table structure for table `password_resets`

DROP TABLE IF EXISTS "password_resets";

CREATE TABLE "password_resets" (
  "email" varchar(255) NOT NULL,
  "token" varchar(255) NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL
);
CREATE INDEX "password_resets_email_index" ON "password_resets" ("email");

-- Table structure for table `personal_access_tokens`

DROP TABLE IF EXISTS "personal_access_tokens";

CREATE TABLE "personal_access_tokens" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "tokenable_type" varchar(255) NOT NULL,
  "tokenable_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "token" varchar(64) NOT NULL,
  "abilities" text DEFAULT NULL,
  "last_used_at" timestamp without time zone NULL DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" ON "personal_access_tokens" ("token");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" ON "personal_access_tokens" ("tokenable_type", "tokenable_id");

-- Table structure for table `product_customization_relations`

DROP TABLE IF EXISTS "product_customization_relations";

CREATE TABLE "product_customization_relations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint DEFAULT NULL,
  "product_id" bigint DEFAULT NULL,
  "product_customization_id" bigint DEFAULT NULL,
  "parent_id" bigint DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "position" bigint DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "user_id-index" ON "product_customization_relations" ("user_id");
CREATE INDEX "product_id-index" ON "product_customization_relations" ("product_id");

-- Table structure for table `product_customizations`

DROP TABLE IF EXISTS "product_customizations";

CREATE TABLE "product_customizations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint DEFAULT NULL,
  "name" varchar(255) DEFAULT NULL,
  "description" text DEFAULT NULL,
  "nutritional_info" text DEFAULT NULL,
  "status" varchar(255) NOT NULL DEFAULT 'ok',
  "show_in_order" varchar(255) NOT NULL DEFAULT 'yes',
  "max_quantity" bigint NOT NULL DEFAULT 0,
  "min_quantity" bigint NOT NULL DEFAULT 0,
  "price" integer DEFAULT NULL,
  "pickup_price" integer NOT NULL DEFAULT 0,
  "is_option" varchar(3) NOT NULL DEFAULT 'yes',
  "is_sold_out" varchar(3) NOT NULL DEFAULT 'no',
  "uuid" varchar(50) NOT NULL DEFAULT '',
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "type" varchar(100) NOT NULL DEFAULT 'simple',
  "default_value" text DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "product_customizations_uuid_unique" ON "product_customizations" ("uuid");
CREATE INDEX "user_id-index_idx" ON "product_customizations" ("user_id");

-- Table structure for table `product_order`

DROP TABLE IF EXISTS "product_order";

CREATE TABLE "product_order" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "product_id" bigint NOT NULL,
  "position" integer NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "user_ud-index" ON "product_order" ("user_id");

-- Table structure for table `products`

DROP TABLE IF EXISTS "products";

CREATE TABLE "products" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "slug" varchar(255) NOT NULL,
  "details" varchar(255) DEFAULT NULL,
  "price" integer NOT NULL,
  "description" text NOT NULL,
  "featured" boolean NOT NULL DEFAULT FALSE,
  "quantity" bigint NOT NULL DEFAULT 10,
  "images" text DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "user_id" bigint NOT NULL,
  "delivery_price" integer NOT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'ok',
  "uuid" varchar(255) NOT NULL,
  "store_id" bigint NOT NULL,
  "keywords" text DEFAULT NULL,
  "deposit_options" text DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "products_name_unique" ON "products" ("name");
CREATE UNIQUE INDEX "products_slug_unique" ON "products" ("slug");
CREATE UNIQUE INDEX "products_uuid_unique" ON "products" ("uuid");
CREATE INDEX "products_store_id_index" ON "products" ("store_id");

-- Table structure for table `sessions`

DROP TABLE IF EXISTS "sessions";

CREATE TABLE "sessions" (
  "id" varchar(255) NOT NULL,
  "user_id" bigint DEFAULT NULL,
  "ip_address" varchar(45) DEFAULT NULL,
  "user_agent" text DEFAULT NULL,
  "payload" text NOT NULL,
  "last_activity" integer NOT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "sessions_user_id_index" ON "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" ON "sessions" ("last_activity");

-- Table structure for table `shoppingcart`

DROP TABLE IF EXISTS "shoppingcart";

CREATE TABLE "shoppingcart" (
  "identifier" varchar(255) NOT NULL,
  "instance" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("identifier","instance")
);

-- Table structure for table `stores`

DROP TABLE IF EXISTS "stores";

CREATE TABLE "stores" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "user_id" bigint NOT NULL,
  "slogan" varchar(255) DEFAULT NULL,
  "slug" varchar(255) NOT NULL,
  "datetime_zone" varchar(255) NOT NULL DEFAULT 'America/New York',
  "locale" varchar(20) NOT NULL DEFAULT 'en_US',
  "delivery_address_id" bigint NOT NULL DEFAULT 0,
  "pickup_address_id" bigint NOT NULL DEFAULT 0,
  "business_hours" text DEFAULT NULL,
  "delivery_options" text DEFAULT NULL,
  "business_phone" varchar(255) DEFAULT NULL,
  "business_photo" text DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "status" varchar(20) DEFAULT 'ok',
  "payment_options" text DEFAULT NULL,
  "delivery_timeframe_options" text DEFAULT NULL,
  "categories" text DEFAULT NULL,
  "currency" varchar(20) NOT NULL DEFAULT 'USD',
  "uuid" varchar(50) NOT NULL DEFAULT uuid(),
  "order_state_config" text DEFAULT NULL,
  "delivery_cost" integer NOT NULL DEFAULT 0,
  "service_fee_options" text DEFAULT NULL,
  "is_open" varchar(1) NOT NULL DEFAULT 'y',
  "is_accepting_orders" varchar(1) NOT NULL DEFAULT 'y',
  "is_published" varchar(1) NOT NULL DEFAULT 'n',
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "stores_name_unique" ON "stores" ("name");
CREATE UNIQUE INDEX "stores_slug_unique" ON "stores" ("slug");
CREATE UNIQUE INDEX "stores_uuid_unique" ON "stores" ("uuid");
CREATE INDEX "stores_user_id_index" ON "stores" ("user_id");
CREATE INDEX "stores_is_open_index" ON "stores" ("is_open");
CREATE INDEX "stores_is_published_index" ON "stores" ("is_published");

-- Table structure for table `team_user`

DROP TABLE IF EXISTS "team_user";

CREATE TABLE "team_user" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "team_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "role" varchar(255) DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "team_user_team_id_user_id_unique" ON "team_user" ("team_id", "user_id");

-- Table structure for table `teams`

DROP TABLE IF EXISTS "teams";

CREATE TABLE "teams" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "personal_team" boolean NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE INDEX "teams_user_id_index" ON "teams" ("user_id");

-- Table structure for table `users`

DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "email_verified_at" timestamp without time zone NULL DEFAULT NULL,
  "password" varchar(255) NOT NULL,
  "uuid" varchar(50) NOT NULL DEFAULT '',
  "datetime_zone" varchar(255) NOT NULL DEFAULT 'America/New York',
  "locale" varchar(20) NOT NULL DEFAULT 'en_US',
  "zelle_phone" varchar(255) DEFAULT NULL,
  "zelle_email" varchar(255) DEFAULT NULL,
  "cash_app_id" varchar(255) DEFAULT NULL,
  "two_factor_secret" text DEFAULT NULL,
  "two_factor_recovery_codes" text DEFAULT NULL,
  "remember_token" varchar(100) DEFAULT NULL,
  "current_team_id" bigint DEFAULT NULL,
  "profile_photo_path" text DEFAULT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  "google_id" varchar(255) DEFAULT NULL,
  "facebook_id" varchar(255) DEFAULT NULL,
  "status" varchar(50) NOT NULL DEFAULT 'ok',
  "delivery_address_id" bigint NOT NULL DEFAULT 0,
  "test_seller" varchar(255) NOT NULL DEFAULT 'n',
  "can_sell" varchar(255) NOT NULL DEFAULT 'n',
  "store_id" bigint DEFAULT NULL,
  "is_system_admin" varchar(3) NOT NULL DEFAULT 'no',
  "is_test_user" varchar(1) NOT NULL DEFAULT 'n',
  "role" varchar(255) NOT NULL DEFAULT 'admin',
  "is_available" varchar(1) NOT NULL DEFAULT 'y',
  "last_location" text DEFAULT NULL,
  "last_location_time" timestamp without time zone NULL DEFAULT NULL,
  "phone" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "users_email_unique" ON "users" ("email");
CREATE INDEX "text_seller-index" ON "users" ("test_seller");
CREATE INDEX "can_sell-index" ON "users" ("can_sell");

-- Table structure for table `websockets_statistics_entries`

DROP TABLE IF EXISTS "websockets_statistics_entries";

CREATE TABLE "websockets_statistics_entries" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY,
  "app_id" varchar(255) NOT NULL,
  "peak_connection_count" integer NOT NULL,
  "websocket_message_count" integer NOT NULL,
  "api_message_count" integer NOT NULL,
  "created_at" timestamp without time zone NULL DEFAULT NULL,
  "updated_at" timestamp without time zone NULL DEFAULT NULL,
  PRIMARY KEY ("id")
);
